# fly.toml app configuration file generated for racing-f1-backend on 2025-05-10T07:56:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'racing-f1-backend'
primary_region = 'mad'

[build]
  dockerfile = 'Dockerfile'

[env]
  DB_HOST = 'racing-db.internal'
  DB_NAME = 'postgres'
  DB_PASSWORD = 'Vip4W18RCT17Ux3'
  DB_PORT = '5432'
  DB_USER = 'postgres'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
